import { ReactComponent as Rating } from "../../images/content/rating.svg";
import like from "../../images/like.png";
import share from "../../images/share.png";

export const customerCard = [
  {
    avatar: null,
    name: 'Аутсорсинговая компания "IT Develope"',
    feedback: "1",
    countImg: "96",
    rating: <Rating />,
    age: "4",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
  {
    avatar: null,
    name: 'Alex Levi',
    technician: "Местный эксперт",
    feedback: "380",
    countImg: "1694",
    rating: <Rating />,
    age: "5",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
  {
    avatar: null,
    name: 'Аутсорсинговая компания "IT Develope"',
    feedback: "1",
    countImg: "96",
    rating: <Rating />,
    age: "4",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
  {
    avatar: null,
    name: 'Alex Levi',
    technician: "Местный эксперт",
    feedback: "380",
    countImg: "1694",
    rating: <Rating />,
    age: "5",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
  {
    avatar: null,
    name: 'Аутсорсинговая компания "IT Develope"',
    feedback: "1",
    countImg: "96",
    rating: <Rating />,
    age: "4",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
  {
    avatar: null,
    name: 'Alex Levi',
    technician: "Местный эксперт",
    feedback: "380",
    countImg: "1694",
    rating: <Rating />,
    age: "5",
    text: "Магазин в котором много чего есть,если надо что-то срочно.Товар хорошего качество,низкие цены",
    like: like,
    share: share,
  },
];
